#!/usr/bin/env bash


# Run PHP-FPM as current user
if [ ! -z "$IDUSER" ]; then
    sed -i "s/user\ \=.*/user\ \= $IDUSER/g" /etc/php/7.3/fpm/pool.d/www.conf

    usermod -u $IDUSER zzz
fi

# Ensure /.composer exists and is writable
if [ ! -d /.composer ]; then
    mkdir /.composer
fi
chmod -R ugo+rw /.composer

# Run a command or supervisord
if [ $# -gt 0 ];then
    # If we passed a command, run it as current user
    exec gosu $IDUSER "$@"
else
    # Otherwise start supervisord
    /usr/bin/supervisord
fi
