version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        CONTAINER_ENV: ${APP_ENV}
    restart: always
    image: shortlink
    ports:
      - ${APP_PORT}:80
    environment:
      CONTAINER_ENV: ${APP_ENV}
      WWWUSER: ${IDUSER}
    volumes:
      - .:/var/www/html
    networks:
      - shortlink
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - shortlinkmysql:/var/lib/mysql
    networks:
      - shortlink
networks:
  shortlink:
    driver: bridge
volumes:
  shortlinkmysql:
    driver: "local"
